apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ template "fullname" . }}-jobmanager
spec:
  replicas: {{ .Values.availability.num_jobmanagers }}
  serviceName: {{ template "fullname" . }}-jobmanager-headless
  selector:
    matchLabels:
      app: {{ template "fullname" . }}-jobmanager
  template:
    metadata:
      labels:
        app: {{ template "fullname" . }}-jobmanager
    spec:
      containers:
      - name: jobmanager
        image: {{ .Values.image }}:{{ .Values.imageTag }}
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        args:
        - jobmanager
        ports:
        - containerPort: 6123
          name: rpc
        - containerPort: 6124
          name: blob
        - containerPort: 8081
          name: ui
        env:
        - name: FLINK_CONF_DIR
          value: /etc/flink
        livenessProbe:
          httpGet:
            path: /overview
            port: 8081
          initialDelaySeconds: 30
          periodSeconds: 10
        resources:
          limits:
            cpu: {{ .Values.resources.jobmanager.limits.cpu }}
            memory: {{ .Values.resources.jobmanager.limits.memory }}
          requests:
            cpu: {{ .Values.resources.jobmanager.requests.cpu }}
            memory: {{ .Values.resources.jobmanager.requests.memory }}
        volumeMounts:
        - name: {{ template "fullname" . }}-flink-config
          mountPath: /etc/flink
        - name: {{ template "fullname" . }}-hadoop-config
          mountPath: /etc/hadoop/conf
        - name: statedate
          mountPath: /statedir
      volumes:
        - name: {{ template "fullname" . }}-flink-config
          configMap:
            name: {{ template "fullname" . }}-flink-config
        - name: {{ template "fullname" . }}-hadoop-config
          configMap:
            name: {{ template "fullname" . }}-hadoop-config
  volumeClaimTemplates:
    - metadata:
        name: statedate
      spec:
        accessModes: [ "ReadWriteMany" ]

        storageClassName: manual
        resources:
          requests:
            storage: 2Gi